# Generated by Django 5.1.3 on 2024-11-24 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinname', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_twd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=30)),
                ('change_24h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BitcoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField()),
                ('twd', models.FloatField()),
                ('eur', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coin')),
            ],
        ),
    ]
